/**
 * Excel Export Constants
 * Centralized configuration for all Excel exports
 */

// Brand colors in ARGB format
const BRAND_COLORS = {
  primary: 'FF9E1F63',
  primaryDark: 'FF721548',
  primaryLight: 'FFCB5B96',
  secondary: 'FF424046',
  secondaryLight: 'FF6A686F',
  secondaryPale: 'FFE2E1E6',
  accentBlue: 'FF005B8C',
  accentCoral: 'FFE05E3D',
  neutralDark: 'FF2D2D2D',
  neutralMid: 'FF717171',
  neutralLight: 'FFF2F2F4',
  white: 'FFFFFFFF',
  success: 'FF00A651',
  warning: 'FFFFA500',
  error: 'FFDC3545'
};

// Default number formats
const NUMBER_FORMATS = {
  currency: '"SAR "#,##0.00',
  currencyNegative: '"SAR "#,##0.00_);[Red]("SAR "#,##0.00)',
  percentage: '0.0%',
  percentageDetailed: '0.00%',
  number: '#,##0',
  numberDecimal: '#,##0.00',
  date: 'dd/mm/yyyy',
  dateTime: 'dd/mm/yyyy hh:mm',
  monthYear: 'mmm yyyy',
  time: 'hh:mm:ss'
};

// Column width presets
const COLUMN_WIDTHS = {
  narrow: 8,
  small: 12,
  medium: 15,
  large: 20,
  wide: 25,
  extraWide: 30,
  text: 35,
  description: 50
};

// Default column widths by content type
const DEFAULT_COLUMN_WIDTHS = {
  id: COLUMN_WIDTHS.narrow,
  count: COLUMN_WIDTHS.small,
  percentage: COLUMN_WIDTHS.medium,
  currency: COLUMN_WIDTHS.medium,
  date: COLUMN_WIDTHS.medium,
  name: COLUMN_WIDTHS.wide,
  description: COLUMN_WIDTHS.description,
  default: COLUMN_WIDTHS.medium
};

// Achievement thresholds
const ACHIEVEMENT_THRESHOLDS = {
  excellent: 100,
  good: 80,
  warning: 60,
  critical: 40
};

// Profit margin thresholds
const PROFIT_MARGIN_THRESHOLDS = {
  excellent: 30,
  good: 20,
  acceptable: 15,
  warning: 10,
  critical: 5
};

// Export file naming patterns
const FILE_NAMING = {
  dateFormat: 'YYYY-MM-DD',
  separator: '-',
  extension: '.xlsx',
  prefix: 'proceed',
  patterns: {
    overview: '{prefix}-overview-{period}-{year}',
    businessUnit: '{prefix}-business-units-{period}-{year}',
    customer: '{prefix}-customers-{period}-{year}',
    trends: '{prefix}-trends-{year}',
    custom: '{prefix}-{type}-{date}'
  }
};

// Sheet naming conventions
const SHEET_NAMES = {
  overview: 'Overview',
  summary: 'Summary',
  details: 'Details',
  businessUnits: 'Business Units',
  customers: 'Customers',
  customerPerformance: 'Customer Performance',
  achievementAnalysis: 'Achievement Analysis',
  serviceAnalysis: 'Service Analysis',
  monthlyTrends: 'Monthly Trends',
  quarterlyTrends: 'Quarterly Trends',
  yearlyComparison: 'Yearly Comparison',
  analysis: 'Analysis',
  raw: 'Raw Data'
};

// Report headers configuration
const REPORT_HEADERS = {
  companyName: 'PROCEED',
  reportPrefix: 'Revenue Dashboard',
  generatedByPrefix: 'Generated by',
  dateTimeFormat: 'DD/MM/YYYY HH:mm:ss'
};

// Data validation rules
const VALIDATION_RULES = {
  minYear: 2020,
  maxYear: 2030,
  validPeriods: ['MTD', 'QTD', 'YTD'],
  validMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  validQuarters: [1, 2, 3, 4],
  maxRowsPerSheet: 1000000,
  maxColumnsPerSheet: 16384
};

// Performance optimization settings
const PERFORMANCE_SETTINGS = {
  batchSize: 1000,
  streamingThreshold: 10000,
  cacheTimeout: 300000, // 5 minutes
  maxConcurrentExports: 5,
  compressionLevel: 6
};

// Error messages
const ERROR_MESSAGES = {
  noData: 'No data available for the selected period',
  invalidPeriod: 'Invalid period specified. Valid periods are: MTD, QTD, YTD',
  invalidYear: `Invalid year. Year must be between ${VALIDATION_RULES.minYear} and ${VALIDATION_RULES.maxYear}`,
  exportFailed: 'Export failed. Please try again.',
  tooManyRows: `Data exceeds maximum rows per sheet (${VALIDATION_RULES.maxRowsPerSheet})`,
  invalidFormat: 'Invalid export format specified',
  missingRequired: 'Required data is missing',
  serverError: 'An unexpected error occurred during export'
};

// Success messages
const SUCCESS_MESSAGES = {
  exportComplete: 'Export completed successfully',
  exportStarted: 'Export process started',
  exportQueued: 'Export has been queued for processing'
};

// Chart configurations
const CHART_CONFIGS = {
  defaultHeight: 15, // rows
  defaultWidth: 10, // columns
  types: ['line', 'column', 'bar', 'pie', 'area', 'scatter'],
  colors: [
    BRAND_COLORS.primary,
    BRAND_COLORS.accentBlue,
    BRAND_COLORS.accentCoral,
    BRAND_COLORS.secondary,
    BRAND_COLORS.success,
    BRAND_COLORS.warning
  ]
};

// Export configuration defaults
const EXPORT_DEFAULTS = {
  includeTimestamp: true,
  includeMetadata: true,
  includeCharts: false,
  includeSummary: true,
  includeAnalysis: false,
  autoSizeColumns: true,
  applyBranding: true,
  compressOutput: true
};

module.exports = {
  BRAND_COLORS,
  NUMBER_FORMATS,
  COLUMN_WIDTHS,
  DEFAULT_COLUMN_WIDTHS,
  ACHIEVEMENT_THRESHOLDS,
  PROFIT_MARGIN_THRESHOLDS,
  FILE_NAMING,
  SHEET_NAMES,
  REPORT_HEADERS,
  VALIDATION_RULES,
  PERFORMANCE_SETTINGS,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
  CHART_CONFIGS,
  EXPORT_DEFAULTS
};